<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-DHLLMMD" failures="2" tests="8" name="RetryFailedTests" time="0.147" errors="0" timestamp="03 Dec 2019 16:38:44 GMT">
  <testcase classname="Test.MyTest" name="test1" time="0.031">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="Test.MyTest" name="test1" time="0.016">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="Test.MyTest" name="test1" time="0.0">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="Test.MyTest" name="test1" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Test.MyTest.test1(MyTest.java:11)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="Test.MyTest" name="test2" time="0.0">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="Test.MyTest" name="test2" time="0.0">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="Test.MyTest" name="test2" time="0.0">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="Test.MyTest" name="test2" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Test.MyTest.test2(MyTest.java:16)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- RetryFailedTests -->
